<?php

class options_page {}
class My_Widget {}
class Foo_Widget {}
class My_Widget_Class {}
class MyTheme_Customize {}


function my_plugin_menu() {}
function my_plugin_page() {}
function mt_add_pages() {}
function register_custom_menu_page() {}
function custom_menu_page() {}
function my_remove_menu_pages() {}
function register_my_custom_submenu_page() {}
function my_custom_submenu_page_callback() {}
function adjust_the_wp_menu() {}
function example_dashboard_widget_function() {}
function example_add_dashboard_widgets() {}
function example_remove_dashboard_widgets() {}
function get_dashboard_widget_options() {}
function get_dashboard_widget_option() {}
function update_dashboard_widget_options() {}
function foobar_func() {}
function bartag_func() {}
function my_shortcode_handler() {}
function myShortCode() {}
function caption_shortcode() {}
function myplugin_activate() {}
function myplugin_deactivate() {}
function frosty_flush_rewrite_rules() {}
function maybe_rewrite_rules() {}
function my_flush_rules() {}
function my_insert_rewrite_rules() {}
function my_insert_query_vars() {}
function keywords_create_rewrite_rules() {}
function feed_dir_rewrite() {}
function appthemes_add_quicktags() {}
function my_callback() {}
function eg_settings_api_init() {}
function eg_setting_section_callback_function() {}
function eg_setting_callback_function() {}
function register_my_setting() {}
function change() {}
function your_admin_notices_action() {}
function edit_term_delete_transient() {}
function mytheme_customize_register() {}
function mytheme_customize_css() {}
function mytheme_customizer_live_preview() {}
function wcpdx_get_movie() {}
function exclude_category() {}
function hwl_home_pagesize() {}
function the_theme_setup() {}
function process_post() {}
function add_header_xua() {}
function search_template_redirect() {}
function themeslug_enqueue_style() {}
function themeslug_enqueue_script() {}
function your_function() {}
function my_tweaked_admin_bar() {}
function restrict_admin() {}
function restrict_admin_with_redirect() {}
function myplugin_settings() {}
function test_load() {}
function load_custom_wp_admin_style() {}
function my_enqueue() {}
function admin_inline_js() {}
function my_custom_admin_head() {}
function my_admin_notice() {}
function foot_monger() {}
function quickEditSmiles() {}
function remove_dashboard_widgets() {}
function my_func() {}
function codex_init() {}
function codex_sync() {}
function my_project_updated_send_email() {}
function set_private_categories() {}
function comment_approved() {}
function comment_inserted() {}
function add_my_rss_node() {}
function add_my_custom_field_node() {}
function Init_theme() {}
function myplugin_setup_options () {}
function myplugin_admin_footer() {}
function prefix_add_my_stylesheet() {}
function my_plugin_admin_init() {}
function my_plugin_admin_menu() {}
function my_plugin_admin_styles() {}
function my_plugin_manage_menu() {}
function theme_styles() {}
function my_delete_user() {}
function add_extra_profile_fields() {}
function childtheme_custom_login() {}
function my_custom_login_logo() {}
function custom_columns() {}
function display_posts_stickiness() {}
function add_sticky_column() {}
function my_custom_pages_columns() {}
function set_custom_edit_book_columns() {}
function add_book_columns() {}
function set_book_columns() {}
function my_password_reset() {}
function update_extra_profile_fields() {}
function extra_profile_fields() {}
function my_profile_update() {}
function display_custom_quickedit_book() {}
function save_book_meta() {}
function admin_edit_foot() {}
function custom_book_column() {}
function myplugin_add_registration_fields() {}
function check_fields() {}
function myplugin_registration_save() {}
function prefix_ajax_add_foobar() {}
function my_ajax() {}
function checkCustomAuthentication() {}
function check_custom_authentication() {}
function clear_transient_on_logout() {}
function add_recipe_counts() {}
function wpautop_control_menu() {}
function kill_feed_rewrites() {}
function install() {}
function uninstall() {}
function activate() {}
function deactivate() {}
function save() {}
function update() {}
